apiVersion: v1
kind: Service
metadata:
  name: flask-application-service
spec:
  selector:
    app: flask-application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30500
  type: NodePort